### ISSUE TITLE
add 'ecr'

### ISSUE THREAD

**Issue by FlorianSchwendinger** [cran-task-views/Optimization#13]
There seems to already exist a **ecr2** package.

**Comment by hwborchers** [comment]
The last version of 'ecr' seems to have appeared in 2017 and got archived. And the last version of ecr2 on Github is from 2018.

It says: "There will be a new release on CRAN soon", nothing happened since then. We could write to the author, Jakob Bossek, but I think we do not add it to the Task View until we hear from the author that he will continue working on the package again.

**Comment by FlorianSchwendinger** [comment]
It seams that in **ecr2** the 2 refers to the major version and currently on CRAN is `2.1.0`. So it is still actively developed and the latest release is on CRAN.
